### ISSUE TITLE
Async actions called infinitely

### ISSUE THREAD

**Issue by 38Slava** [RealScout/redux-infinite-scroll#3]
### Component

``` javascript
const mapStateToProps = (state) => ({
  data: state.data
});
class DataView extends Component {
  componentWillMount () {
    this.props.getData();
  }
  static propTypes = {
    data: PropTypes.object.isRequired,
    getData: PropTypes.func.isRequired
  };
  _loadMore = () => {
    this.props.getData();
  }
  _renderItems = () => {
    return _.map(this.props.data.response, (item) => <MediaItem key={item.id} {...item} />);
  }
  render () {
    if (!this.props.data.response) return (<p>Loading</p>);
    return (
        <InfiniteScroll
          items={this._renderItems()}
          loadMore={this._loadMore}
        />
    )
  }
}
export default connect(mapStateToProps, dataActions)(DataView);
```
### Action

``` javascript
export const getData = (skip = 0): Action => {
  return (dispatch) => {
    dispatch(getDataRequest());
    return fetcher.get('/api/data')
      .then((response) => dispatch(getDataSuccess(response.data)))
      .catch((err) => dispatch(getDataFail(err)));
  };
};
```
### Reducer

``` javascript
const reducer = (state = {}, action) => {
  switch (action.type) {
    case Action.GET_DATA_REQUEST:
      return state;
    case Action.GET_DATA_SUCCESS:
      return {
        ...state,
        response: action.payload.response
      };
    case Action.GET_DATA_FAIL:
      return {
        error: action.payload.error
      };
    default:
      return state;
  }
};
```

So when i call loadMore it calls in a loop. What i doing wrong? Could this be related with dispatching in async action?

**Comment by dcurletti** [comment]
Looks like I'll finally be getting to this in the next few days.

**Comment by dcurletti** [comment]
@38Slava I finally got around looking into this and your problem is that the default prop `containerHeight` is 100%, which means that if you are trying to use the infinite scroll on an element that is scrollable, you need to pass a set height to it. 

In addition, if you are trying to listen to the window, then you need to make sure that in your reducer you are checking whether you have received all of the possible items.  If there are no more items available from the server, then you should pass `false` to the `hasMore` prop.

I realize now that this requires two sets of instructions: when you are trying to listen to the window and when you are trying to listen to a div scroll.
